config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'rates#convert'

get  'rates/series'
get  'rates/convert'
post 'rates/get_series'
post 'rates/convert_amount'

get  'admin/list_currencies'
get  'admin/get_currencies'
get  'admin/save_currencies'
get  'admin/delete_currencies'

get  'admin/index'
get  'admin/view_config'
get  'admin/update_config'
post 'admin/save_config'

get  'api/currencies'
get  'api/series'
post 'api/convert'

end

app/models/config.rb
class Config < ApplicationRecord
	validates :url, :apikey, presence: true
end

app/views/admin/config/update.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<div class="btn-toolbar mb-2 mb-md-0">
	<div class="btn-group me-2">
      <%= link_to({:controller => 'admin', :action => 'index'}) do %>
      <button type="button" class="btn btn-sm btn-outline-secondary menu">Back</button>
      <% end %>
  </div>
</div>
</div>

<div class="card text-center shadow p-3 mb-5 bg-white rounded">
  <div class="card-body ">
    <div class="d-flex justify-content-center">
      <div class="field form-group">
      	<%= form_with scope: "params", url: admin_save_config_path, local: true, data: { turbo: false }, method: :post do |form| %>
      	<div class="field form-group">
      		<%= form.text_field :url, class:"form-control", placeholder: @config.url, value: @config.url %>
      	</div>
				<div class="field form-group">
					<%= form.text_field :apikey, class:"form-control", placeholder: @config.apikey, value: @config.apikey %>
				</div>
				<div>
					<%= form.submit "Update" %>
				</div>
				<% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/config/view.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<div class="btn-toolbar mb-2 mb-md-0">
	<div class="btn-group me-2">
      <%= link_to({:controller => 'admin', :action => 'index'}) do %>
      <button type="button" class="btn btn-sm btn-outline-secondary menu">Back</button>
      <% end %>
  </div>
</div>
</div>

<div class="card text-center shadow p-3 mb-5 bg-white rounded">
  <div class="card-body ">
    <div class="d-flex justify-content-center">
      <div class="field form-group">
      	<table class="table table-bordered table-striped mb-0 fitwidth">
      		<thead>
      			<tr>
      				<th scope="col">Id</th>
      				<th scope="col">Url</th>
      				<th scope="col">Apikey</th>
      			</tr>
      		</thead>
      		<tbody>
      			<tr>
      				<td> <%= @config["id"] %> </td>
      				<td> <%= @config["url"] %> </td>
      				<td> <%= @config["apikey"] %> </td>
      			</tr>
      		</tbody>
      	</table>
      </div>
    </div>
  </div>
</div>