config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'rates#convert'

get  'rates/series'
get  'rates/convert'
post 'rates/get_series'
post 'rates/convert_amount'

get  'admin/list_currencies'
get  'admin/get_currencies'
get  'admin/save_currencies'
get  'admin/delete_currencies'

get  'admin/index'
get  'admin/view_config'
get  'admin/update_config'
post 'admin/save_config'

get  'api/currencies'
get  'api/series'
post 'api/convert'

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<header class="navbar navbar-dark sticky-top bg-blue-mine flex-md-nowrap p-0 shadow fullwidth">
    <%= link_to root_path, class: "navbar-brand col-md-3 col-lg-2 me-0 fs-6 pad3px-left" do %>
    <%= image_tag 'logo.png' %>
    <% end %>
    <button class="navbar-toggler d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
</header>

app/views/home/_sidebar.html.erb
 <nav id="sidebarMenu" class="sidebar col-md-3 col-lg-3 d-md-block bg-light collapse pad3px-left" style="">
      <div class="position-sticky sidebar-sticky ">
        <ul class="nav flex-column">
          <li class="nav-item hover-overlay">
            <%= link_to rates_convert_path, class: "nav-link pad3px link-grey" do %>
            <span data-feather="bar-chart-2" class="align-text-bottom"></span>
            Convert
            <% end %>
          </li>
          <li class="nav-item hover-overlay">
            <%= link_to rates_series_path, class: "nav-link pad3px link-grey" do %>
            <span data-feather="bar-chart-2" class="align-text-bottom"></span>
              Timeseries
            <% end %>
          </li>
          <li class="nav-item hover-overlay">
            <%= link_to admin_list_currencies_path, class: "nav-link pad3px link-grey" do %>
            <span data-feather="home" class="align-text-bottom"></span>
            Currencies
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item hover-overlay">
              <%= link_to admin_index_path, class: "nav-link pad3px link-grey" do %>
              <span data-feather="home" class="align-text-bottom"></span>
              Admin
              <% end %>
              <li class="nav-item hover-overlay">
                <%= link_to destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link pad3px link-grey" do %>
                <span data-feather="home" class="align-text-bottom"></span>
                Sign out
                <% end %>
              </li>
            </li>
          <% else %>
            <li class="nav-item hover-overlay">
              <%= link_to new_user_session_path, class: "nav-link pad3px link-grey" do %>
              <span data-feather="home" class="align-text-bottom"></span>
              Log in
              <% end %>
            </li>  
          <% end %>
        </ul>
      </div>
    </nav>