config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'rates#convert'

get  'rates/series'
get  'rates/convert'
post 'rates/get_series'
post 'rates/convert_amount'

get  'admin/list_currencies'
get  'admin/get_currencies'
get  'admin/save_currencies'
get  'admin/delete_currencies'

get  'admin/index'
get  'admin/view_config'
get  'admin/update_config'
post 'admin/save_config'

get  'api/currencies'
get  'api/series'
post 'api/convert'

end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :currency, class_name: "Currency", foreign_key: :base, primary_key: :code
	validates :date, :rate, :base, :to, presence: true
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

require 'json'

def queries
  QueryController.new
end

def convert
  @currencies = Currency.all
  @currencies_code = Currency.pluck(:code)
  render "rates/convert"
end

def series
  @currencies = Currency.all
  #@currencies = Currency.pluck(:code)
  render "rates/series"
end

def convert_amount
  form_params = params.require(:params).permit(:from, :to, :amount, :date)
  p form_params

  if queries.validator( {:params => form_params, :method => "convert_amount"} )
    Rails.logger.debug "Validator passed"
    @response = JSON.parse(queries.convert_amount(form_params))
    Rails.logger.debug "Response #{@response}"
  else
    @response = { "success" => false }
  end
  
  Rails.logger.debug "Response: #{@response}"
  render 'rates/convert_result'
end

def get_series
  
  form_params = params.require(:params).permit(:start_date, :to_date, :from, :to)
  p form_params

  if queries.validator({:params => form_params, :method => "get_series"})
    @response = queries.series(form_params)
  else
    @response = { "success" => false }
  end
  
  p @response
  render 'rates/series_result'
end

end

app/helpers/api/rates_helper.rb
module Api::RatesHelper
end

app/views/rates/convert.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pad3px-top mb-3 border-bottom" data-controller="datepicker">
  <h4 class="h4">Convert</h4>
</div>

<div class="card shadow p-3 mb-5 bg-white rounded">
  <div class="card-body centering">
    <%= form_with scope: "params", url: rates_convert_amount_url, local: true, data: { turbo: false }, method: :post do |form| %>
    
    <div class="seriesbody" >

      <div class="seriesbodydiv1">
        <%= form.number_field :amount, step: 0.5, type:'text', 'id':'input_field','inputmode':'decimal', class:"form-control", placeholder: "100", value: 100 %>
        <%= form.text_field :date, class: "form-control mydatepicker", placeholder: "Today", 'data-provide':"datepicker", 'id':'mydatepicker' %>
        <div class="input-group-addon" id="datepicker-container">
          <span class="glyphicon glyphicon-th"></span>
        </div>
      </div>

      <div class="seriesbodydiv2">
        <div class="nopadding dropdown form-group w-40">        
                <button class="btn" type="button" id="dropdownMenuButton">
                  From
                </button>
                <%= form.hidden_field :from %>
                <button type="button" class="nopadding btn dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="currencySelectButton">
                      <% @currencies.each do |currency| %>
                        <%= content_tag(:li, content_tag(:div, content_tag(:div, currency["desc"], options={'class':'div1'}) + content_tag(:div, currency["code"], options={'class':'div2 currency-flag currency-flag-'+currency["code"].downcase, 'id':'currency-from'}), options={'class':'parent dropdown-item'}))%>
                      <% end %>
                </ul>
              </div>

              <div class="nopadding dropdown form-group w-40">
                <button class="btn" type="button" id="dropdownMenuButton">
                  To
                </button>
                <%= form.hidden_field :to %>
                <button type="button" class="nopadding btn dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="currencySelectButton">
                      <% @currencies.each do |currency| %>
                        <%= content_tag(:li, content_tag(:div, content_tag(:div, currency["desc"], options={'class':'div1'}) + content_tag(:div, currency["code"], options={'class':'div2 currency-flag currency-flag-'+currency["code"].downcase}), options={'class':'parent dropdown-item'}))%>
                      <% end %>
                </ul>
        </div>
      </div>
    
      <div class="seriesbodydiv3  pad8px-top">
      <%= form.submit "Convert", class:"btn btn-light btnhover" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/rates/convert_result.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <%= link_to({:controller => 'rates', :action => 'convert'}) do %>
      <button type="button" class="btn btn-sm btn-outline-secondary">Back</button>
      <% end %>
    </div>
  </div>
</div>

<div class="card text-center shadow p-3 mb-5 bg-white rounded">
  <div class="card-body ">
    <div class="d-flex justify-content-center">
      <div class="field form-group ">
      <br>
      <% if @response["success"] == true %>
        <div class="container">
          <% text = "#{number_to_currency(@response["amount"], unit: "")} #{@response["from"]} = #{number_to_currency(@response["result"], unit: "")} #{@response["to"]}" %>
          <h6> <%= text %> </h6>
          <% text = "on #{@response["date"]} rate: #{@response["rate"]}" %>
          <p> <%= text %> </p>
      <% else %>
        <p> Error occurred, response was not successful </p>
        <p> res: </p>
	<%= p @response %>
      <% end %>
    </div>
  </div>
  </div>
</div>

app/views/rates/series.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pad3px-top mb-3 border-bottom" data-controller="datepicker">
  <h4 class="h4">Timeseries</h4>
</div>

<div class="card shadow p-3 mb-5 bg-white rounded">
  
  <div class="card-body centering">
    <%= form_with scope: "params", url: rates_get_series_url,local:true, data: { turbo: false }, method: :post do |form| %>
    
    <div class="seriesbody" >

      <div class="seriesbodydiv1">
      <%= form.text_field :start_date, class: "form-control mydatepicker", placeholder: "From", 'data-provide':"datepicker", 'id':'mydatepicker' %>
      <div class="input-group-addon" id="datepicker-container">
        <span class="glyphicon glyphicon-th"></span>
      </div>
      <%= form.text_field :to_date, class: "form-control mydatepicker", placeholder: "To", 'data-provide':"datepicker", 'id':'mydatepicker' %>
      </div>

      <div class="seriesbodydiv2">
        <div class="nopadding dropdown form-group w-40">        
          <button class="btn" type="button" id="dropdownMenuButton">
            From
          </button>
          <%= form.hidden_field :from %>
          <button type="button" class="nopadding btn dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                <% @currencies.each do |currency| %>
                  <%= content_tag(:li, content_tag(:div, content_tag(:div, currency["desc"], options={'class':'div1'}) + content_tag(:div, currency["code"], options={'class':'div2 currency-flag currency-flag-'+currency["code"].downcase,'id':'currency-from'}),options={'class':'parent dropdown-item'}))%>
                <% end %>
          </ul>
        </div>

        <div class="nopadding dropdown form-group w-40">
          <button class="btn" type="button" id="dropdownMenuButton">
            To
          </button>
          <%= form.hidden_field :to %>
          <button type="button" class="nopadding btn dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                <% @currencies.each do |currency| %>
                  <%= content_tag(:li, content_tag(:div, content_tag(:div, currency["desc"], options={'class':'div1'}) + content_tag(:div, currency["code"], options={'class':'div2 currency-flag currency-flag-'+currency["code"].downcase}), options={'class':'parent dropdown-item'}))%>
                <% end %>
          </ul>
        </div>
      </div>


      <div class="seriesbodydiv3 pad8px-top">
        <%= form.submit "Process", class:"btn btn-light btnhover " %>
      </div>
      <% end %>
      </div>
  </div>
</div>

app/views/rates/series_result.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <%= link_to({:controller => 'rates', :action => 'series'}) do %>
      <button type="button" class="btn btn-sm btn-outline-secondary">Back</button>
      <% end %>
    </div>
  </div>
</div>
<h2>Timeseries</h2>
<div class="container ">
<% if @response["success"] == true %>
<%= area_chart(@response["series"], precision: 5) %>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Rate</th>
        <th scope="col">From</th>
        <th scope="col">To</th>
      </tr>
    </thead>
    <tbody>
      <% @response["series"].each do | key, value | %>
      <tr>
        <td> <%= key %> </td>
        <td> <%= value %> </td>
        <td> <%= @response["from"] %></td>
        <td> <%= @response["to"] %> </td>
      </tr>
        <% end %>
      </tbody>
    </table>
</div>
<% else %>
<div class="container">
  <p> Error occurred, response was not successful  </p>
</div>
<% end %>